# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Email-Valid
version:      0.176
version_from: lib/Email/Valid.pm
installdirs:  site
requires:
    Mail::Address:                 0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
